# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md

fos_elastica:
    serializer: ~
    clients:
        # local: {host: 127.0.0.1, port: 9200 } # { url: 'http://127.0.0.1:9200' }
        search:
            host: '%env(SEARCH_HOST)%'
            port: '%env(SEARCH_PORT)%'
            username: '%env(SEARCH_USERNAME)%'
            password: '%env(SEARCH_PASSWORD)%'
        # url: { url: '%env(SEARCHBOX_URL)%' }
    indexes:
        message:
            client: search
            types:
                Message:
                    serializer:
                        groups: [Default, search]
                    properties: # in addition to serialization
                        time: {type: 'date'}
                    persistence:
                        driver: orm
                        model:  App\Entity\Message
                        provider: ~
                        listener: '%elastica_listener%'
                        repository: App\Repository\MessageSearchRepository
